/**
 * API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RiskFlagDto } from './riskFlagDto';
import { SummaryDto } from './summaryDto';
import { ClauseDto } from './clauseDto';


export interface AnalysisResultDto { 
    /**
     * Array of contract summaries
     */
    summaries: Array<SummaryDto>;
    /**
     * Array of contract risk flags
     */
    riskFlags: Array<RiskFlagDto>;
    /**
     * Array of contract clauses
     */
    clauses: Array<ClauseDto>;
}

