/**
 * API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileDto } from './fileDto';


export interface AuthUpdateDto { 
    photo?: FileDto;
    firstName?: string;
    lastName?: string;
    email?: string;
    password?: string;
    oldPassword?: string;
}

