/**
 * API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ClauseDto { 
    /**
     * Clause ID
     */
    id: string;
    /**
     * Clause number
     */
    number: string;
    /**
     * Text of the clause
     */
    text: string;
    type?: ClauseDto.TypeEnum;
    isReviewed: boolean;
    isApproved: boolean;
    suggestedText?: string;
    contractId: string;
    analysisId?: string;
    startIndex?: number;
    endIndex?: number;
    title?: string;
    classification?: string;
    riskLevel?: ClauseDto.RiskLevelEnum;
    riskJustification?: string;
    entities?: string;
    amounts?: string;
    dates?: string;
    legalReferences?: string;
    obligation?: string;
    confidence?: number;
    createdAt: string;
    updatedAt: string;
}
export namespace ClauseDto {
    export const TypeEnum = {
        Termination: 'TERMINATION',
        Confidentiality: 'CONFIDENTIALITY',
        Indemnification: 'INDEMNIFICATION',
        Liability: 'LIABILITY',
        IntellectualProperty: 'INTELLECTUAL_PROPERTY',
        GoverningLaw: 'GOVERNING_LAW',
        DisputeResolution: 'DISPUTE_RESOLUTION',
        ForceMajeure: 'FORCE_MAJEURE',
        Assignment: 'ASSIGNMENT',
        Notices: 'NOTICES',
        Severability: 'SEVERABILITY',
        EntireAgreement: 'ENTIRE_AGREEMENT',
        Amendment: 'AMENDMENT',
        Waiver: 'WAIVER',
        Counterparts: 'COUNTERPARTS',
        Headings: 'HEADINGS',
        Definitions: 'DEFINITIONS',
        Payment: 'PAYMENT',
        Term: 'TERM',
        Other: 'OTHER'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
    export const RiskLevelEnum = {
        High: 'HIGH',
        Medium: 'MEDIUM',
        Low: 'LOW'
    } as const;
    export type RiskLevelEnum = typeof RiskLevelEnum[keyof typeof RiskLevelEnum];
}


