/**
 * API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateRepoDto { 
    entityType: CreateRepoDto.EntityTypeEnum;
    entityId: string;
}
export namespace CreateRepoDto {
    export const EntityTypeEnum = {
        Contract: 'contract',
        Template: 'template'
    } as const;
    export type EntityTypeEnum = typeof EntityTypeEnum[keyof typeof EntityTypeEnum];
}


