/**
 * API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RiskFlagDto { 
    /**
     * Risk flag ID
     */
    id: string;
    /**
     * Type of risk
     */
    type: RiskFlagDto.TypeEnum;
    /**
     * Severity of risk
     */
    severity: RiskFlagDto.SeverityEnum;
    description: string;
    suggestedResolution?: string;
    isReviewed: boolean;
    isResolved: boolean;
    reviewerComments?: string;
    status: RiskFlagDto.StatusEnum;
    notes: string;
    analysisId?: string;
    confidence?: number;
    contractId: string;
    clauseId?: string;
    createdAt: string;
    updatedAt: string;
}
export namespace RiskFlagDto {
    export const TypeEnum = {
        Compliance: 'COMPLIANCE',
        Financial: 'FINANCIAL',
        Legal: 'LEGAL',
        Operational: 'OPERATIONAL',
        Reputational: 'REPUTATIONAL',
        MissingClause: 'MISSING_CLAUSE',
        Deviation: 'DEVIATION',
        ComplianceIssue: 'COMPLIANCE_ISSUE',
        AmbiguousLanguage: 'AMBIGUOUS_LANGUAGE',
        UnfairTerms: 'UNFAIR_TERMS',
        DataProtection: 'DATA_PROTECTION',
        IntellectualProperty: 'INTELLECTUAL_PROPERTY',
        Liability: 'LIABILITY',
        Termination: 'TERMINATION',
        Other: 'OTHER'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
    export const SeverityEnum = {
        Low: 'LOW',
        Medium: 'MEDIUM',
        High: 'HIGH'
    } as const;
    export type SeverityEnum = typeof SeverityEnum[keyof typeof SeverityEnum];
    export const StatusEnum = {
        Open: 'OPEN',
        Resolved: 'RESOLVED',
        Ignored: 'IGNORED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


