/**
 * API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StandardClauseDto { 
    id: number;
    name: string;
    type: string;
    contractType: string;
    text: string;
    jurisdiction?: string;
    version?: string;
    allowedDeviations?: number;
    createdAt: string;
    updatedAt: string;
    previousVersionId?: number;
}

