/**
 * API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SummaryDto { 
    /**
     * Summary ID
     */
    id: string;
    /**
     * Type of summary
     */
    type: SummaryDto.TypeEnum;
    /**
     * Summary text
     */
    text: string;
    /**
     * Whether the summary is reviewed
     */
    isReviewed: boolean;
    reviewerComments?: string;
    /**
     * Contract ID
     */
    contractId: string;
    clauseId?: string;
    createdAt: string;
    updatedAt: string;
}
export namespace SummaryDto {
    export const TypeEnum = {
        Full: 'FULL',
        Clause: 'CLAUSE',
        Risk: 'RISK',
        Compliance: 'COMPLIANCE'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


