/**
 * API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateRiskFlagDto { 
    status: UpdateRiskFlagDto.StatusEnum;
    notes?: string;
}
export namespace UpdateRiskFlagDto {
    export const StatusEnum = {
        Open: 'OPEN',
        Resolved: 'RESOLVED',
        Ignored: 'IGNORED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


