/**
 * API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateRuleDto { 
    name?: string;
    description?: string;
    pattern?: string;
    similarityThreshold?: number;
    deviationAllowedPct?: number;
}

