/**
 * API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoleDto } from './roleDto';
import { StatusDto } from './statusDto';
import { FileDto } from './fileDto';


export interface UpdateUserDto { 
    email?: string;
    password?: string;
    firstName?: string;
    lastName?: string;
    photo?: FileDto;
    role?: RoleDto;
    status?: StatusDto;
}

