/**
 * API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Role } from './role';
import { Status } from './status';
import { FileType } from './fileType';


export interface User { 
    id: number;
    email: string;
    provider: string;
    socialId: string;
    firstName: string;
    lastName: string;
    photo: FileType;
    role: Role;
    status: Status;
    createdAt: string;
    updatedAt: string;
    deletedAt: object;
}

