export * from './auth.service';
import { AuthService } from './auth.service';
export * from './auth.serviceInterface';
export * from './contracts.service';
import { ContractsService } from './contracts.service';
export * from './contracts.serviceInterface';
export * from './files.service';
import { FilesService } from './files.service';
export * from './files.serviceInterface';
export * from './home.service';
import { HomeService } from './home.service';
export * from './home.serviceInterface';
export * from './rules.service';
import { RulesService } from './rules.service';
export * from './rules.serviceInterface';
export * from './standardClauses.service';
import { StandardClausesService } from './standardClauses.service';
export * from './standardClauses.serviceInterface';
export * from './templates.service';
import { TemplatesService } from './templates.service';
export * from './templates.serviceInterface';
export * from './users.service';
import { UsersService } from './users.service';
export * from './users.serviceInterface';
export * from './versionControl.service';
import { VersionControlService } from './versionControl.service';
export * from './versionControl.serviceInterface';
export const APIS = [AuthService, ContractsService, FilesService, HomeService, RulesService, StandardClausesService, TemplatesService, UsersService, VersionControlService];
