/**
 * API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AuthAppleLoginDto } from '../model/models';
import { AuthConfirmEmailDto } from '../model/models';
import { AuthEmailLoginDto } from '../model/models';
import { AuthFacebookLoginDto } from '../model/models';
import { AuthForgotPasswordDto } from '../model/models';
import { AuthGoogleLoginDto } from '../model/models';
import { AuthRegisterLoginDto } from '../model/models';
import { AuthResetPasswordDto } from '../model/models';
import { AuthUpdateDto } from '../model/models';
import { LoginResponseDto } from '../model/models';
import { RefreshResponseDto } from '../model/models';
import { User } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AuthServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param authAppleLoginDto 
     */
    authAppleControllerLoginV1(authAppleLoginDto: AuthAppleLoginDto, extraHttpRequestParams?: any): Observable<LoginResponseDto>;

    /**
     * 
     * 
     * @param authConfirmEmailDto 
     */
    authControllerConfirmEmailV1(authConfirmEmailDto: AuthConfirmEmailDto, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param authConfirmEmailDto 
     */
    authControllerConfirmNewEmailV1(authConfirmEmailDto: AuthConfirmEmailDto, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    authControllerDeleteV1(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param authForgotPasswordDto 
     */
    authControllerForgotPasswordV1(authForgotPasswordDto: AuthForgotPasswordDto, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param authEmailLoginDto 
     */
    authControllerLoginV1(authEmailLoginDto: AuthEmailLoginDto, extraHttpRequestParams?: any): Observable<LoginResponseDto>;

    /**
     * 
     * 
     */
    authControllerLogoutV1(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    authControllerMeV1(extraHttpRequestParams?: any): Observable<User>;

    /**
     * 
     * 
     */
    authControllerRefreshV1(extraHttpRequestParams?: any): Observable<RefreshResponseDto>;

    /**
     * 
     * 
     * @param authRegisterLoginDto 
     */
    authControllerRegisterV1(authRegisterLoginDto: AuthRegisterLoginDto, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param authResetPasswordDto 
     */
    authControllerResetPasswordV1(authResetPasswordDto: AuthResetPasswordDto, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param authUpdateDto 
     */
    authControllerUpdateV1(authUpdateDto: AuthUpdateDto, extraHttpRequestParams?: any): Observable<User>;

    /**
     * 
     * 
     * @param authFacebookLoginDto 
     */
    authFacebookControllerLoginV1(authFacebookLoginDto: AuthFacebookLoginDto, extraHttpRequestParams?: any): Observable<LoginResponseDto>;

    /**
     * 
     * 
     * @param authGoogleLoginDto 
     */
    authGoogleControllerLoginV1(authGoogleLoginDto: AuthGoogleLoginDto, extraHttpRequestParams?: any): Observable<LoginResponseDto>;

}
