/**
 * API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AnalysisResultDto } from '../model/models';
import { UpdateRiskFlagDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ContractsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Analyze a contract using AI
     * 
     * @param id Contract ID
     */
    contractControllerAnalyzeContract(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Ask a question about the contract
     * 
     * @param id Contract ID
     */
    contractControllerAskQuestion(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Upload a contract file
     * 
     * @param file 
     * @param contractType 
     */
    contractControllerCreate(file?: Blob, contractType?: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Export contract analysis
     * 
     * @param id Contract ID
     */
    contractControllerExportAnalysis(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get all contracts
     * 
     */
    contractControllerFindAll(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get a contract by id
     * 
     * @param id Contract ID
     */
    contractControllerFindOne(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get full contract analysis
     * 
     * @param id Contract ID
     */
    contractControllerGetAnalysis(id: string, extraHttpRequestParams?: any): Observable<AnalysisResultDto>;

    /**
     * Get chat history
     * 
     * @param id Contract ID
     */
    contractControllerGetChat(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get contract Q&amp;A
     * 
     * @param id Contract ID
     */
    contractControllerGetContractQnA(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get contract reviews
     * 
     * @param id Contract ID
     */
    contractControllerGetContractReviews(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get contract risks
     * 
     * @param id Contract ID
     */
    contractControllerGetContractRisks(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get contract summaries
     * 
     * @param id Contract ID
     */
    contractControllerGetContractSummary(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Ingest a contract using hybrid AI
     * 
     * @param id Contract ID
     * @param body Contract ingestion data
     * @param body2 
     */
    contractControllerHybridIngest(id: string, body: object, body2: object, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Search contract clauses using hybrid AI
     * 
     * @param q Search query
     * @param id Contract ID
     */
    contractControllerHybridSearch(q: string, id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Delete a contract
     * 
     * @param id Contract ID
     */
    contractControllerRemove(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Submit a chat question
     * 
     * @param id Contract ID
     */
    contractControllerSubmitChat(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Update a contract
     * 
     * @param id Contract ID
     * @param body 
     */
    contractControllerUpdate(id: string, body: object, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Update risk flag status
     * 
     * @param id Contract ID
     * @param riskId Risk ID
     * @param updateRiskFlagDto 
     */
    contractControllerUpdateRiskFlag(id: string, riskId: string, updateRiskFlagDto: UpdateRiskFlagDto, extraHttpRequestParams?: any): Observable<{}>;

}
