/**
 * API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateRuleDto } from '../model/models';
import { UpdateRuleDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface RulesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create rule
     * 
     * @param createRuleDto 
     */
    rulesControllerCreate(createRuleDto: CreateRuleDto, extraHttpRequestParams?: any): Observable<object>;

    /**
     * List rules
     * 
     */
    rulesControllerFindAll(extraHttpRequestParams?: any): Observable<object>;

    /**
     * Get rule by id
     * 
     * @param id 
     */
    rulesControllerFindOne(id: string, extraHttpRequestParams?: any): Observable<object>;

    /**
     * Delete rule
     * 
     * @param id 
     */
    rulesControllerRemove(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Update rule
     * 
     * @param id 
     * @param updateRuleDto 
     */
    rulesControllerUpdate(id: string, updateRuleDto: UpdateRuleDto, extraHttpRequestParams?: any): Observable<object>;

}
