/**
 * API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { StandardClauseDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface StandardClausesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create a new standard clause
     * 
     * @param body 
     */
    standardClausesControllerCreate(body: object, extraHttpRequestParams?: any): Observable<StandardClauseDto>;

    /**
     * Get all standard clauses
     * 
     */
    standardClausesControllerFindAll(extraHttpRequestParams?: any): Observable<Array<StandardClauseDto>>;

    /**
     * Get standard clauses by contract type
     * 
     * @param contractType 
     */
    standardClausesControllerFindByContractType(contractType: string, extraHttpRequestParams?: any): Observable<Array<StandardClauseDto>>;

    /**
     * Get standard clauses by type
     * 
     * @param type 
     */
    standardClausesControllerFindByType(type: string, extraHttpRequestParams?: any): Observable<Array<StandardClauseDto>>;

    /**
     * Get a standard clause by id
     * 
     * @param id 
     */
    standardClausesControllerFindOne(id: string, extraHttpRequestParams?: any): Observable<StandardClauseDto>;

    /**
     * Delete a standard clause
     * 
     * @param id 
     */
    standardClausesControllerRemove(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Update a standard clause
     * 
     * @param id 
     * @param body 
     */
    standardClausesControllerUpdate(id: string, body: object, extraHttpRequestParams?: any): Observable<StandardClauseDto>;

}
