/**
 * API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';



import { Configuration }                                     from '../configuration';



export interface TemplatesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param body 
     */
    templatesControllerCreate(body: object, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    templatesControllerFindAll(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param jurisdiction 
     */
    templatesControllerFindByJurisdiction(jurisdiction: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param type 
     */
    templatesControllerFindByType(type: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    templatesControllerFindOne(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    templatesControllerRemove(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     * @param body 
     */
    templatesControllerUpdate(id: number, body: object, extraHttpRequestParams?: any): Observable<{}>;

}
