/**
 * API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateUserDto } from '../model/models';
import { InfinityPaginationUserResponseDto } from '../model/models';
import { UpdateUserDto } from '../model/models';
import { User } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface UsersServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param createUserDto 
     */
    usersControllerCreateV1(createUserDto: CreateUserDto, extraHttpRequestParams?: any): Observable<User>;

    /**
     * 
     * 
     * @param page 
     * @param limit 
     * @param filters 
     * @param sort 
     */
    usersControllerFindAllV1(page?: number, limit?: number, filters?: string, sort?: string, extraHttpRequestParams?: any): Observable<InfinityPaginationUserResponseDto>;

    /**
     * 
     * 
     * @param id 
     */
    usersControllerFindOneV1(id: string, extraHttpRequestParams?: any): Observable<User>;

    /**
     * 
     * 
     * @param id 
     */
    usersControllerRemoveV1(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     * @param updateUserDto 
     */
    usersControllerUpdateV1(id: string, updateUserDto: UpdateUserDto, extraHttpRequestParams?: any): Observable<User>;

}
