/**
 * API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateBranchDto } from '../model/models';
import { CreateCommitDto } from '../model/models';
import { CreateRepoDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface VersionControlServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create commit
     * 
     * @param id 
     * @param createCommitDto 
     */
    versionControlControllerCommit(id: string, createCommitDto: CreateCommitDto, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Create branch
     * 
     * @param id 
     * @param createBranchDto 
     */
    versionControlControllerCreateBranch(id: string, createBranchDto: CreateBranchDto, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Create repository
     * 
     * @param createRepoDto 
     */
    versionControlControllerCreateRepo(createRepoDto: CreateRepoDto, extraHttpRequestParams?: any): Observable<{}>;

}
